### ISSUE TITLE
Increase flexiblity of `score_models()`

### ISSUE THREAD

**Issue by Bisaloo** [covid19-forecast-hub-europe/EuroForecastHub#3]
From a comment in https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/683.

Increase flexiblity of `score_models()` by adding arguments:

1. the inclusion criteria for "Overall" (1/2 of locations)
2. an option to return e.g. un-averaged scores by "target_end_date" (so that one could use it to get all the 'raw' scores)
3. a `summarise_by` argument forwarded to all the calls to `scoringutils::eval_forecasts()`

**Comment by sbfnk** [comment]
(just noting that point (3) is the more general version of point (2))
